#!/bin/sh

DST=dist/cbxv_mac_x86_64

go build -o out/cbxv cmd/cbxv/*.go

# mk dst
mkdir -p $DST
mkdir -p $DST/lib

cp out/cbxv $DST

# List generated with otool -L
cp /usr/local/opt/glib/lib/libgmodule-2.0.0.dylib $DST/
cp /usr/local/opt/glib/lib/libgobject-2.0.0.dylib $DST/
cp /usr/local/opt/glib/lib/libglib-2.0.0.dylib $DST/
cp /usr/local/opt/glib/lib/libgio-2.0.0.dylib $DST/
cp /usr/local/opt/pango/lib/libpangocairo-1.0.0.dylib $DST/
cp /usr/local/opt/pango/lib/libpango-1.0.0.dylib $DST/
cp /usr/local/opt/gtk+3/lib/libgdk-3.0.dylib $DST/
cp /usr/local/opt/cairo/lib/libcairo-gobject.2.dylib $DST/
cp /usr/local/opt/cairo/lib/libcairo.2.dylib $DST/
cp /usr/local/opt/gdk-pixbuf/lib/libgdk_pixbuf-2.0.0.dylib $DST/
cp /usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib $DST/
cp /usr/local/opt/gettext/lib/libintl.8.dylib $DST/
cp /usr/local/opt/atk/lib/libatk-1.0.0.dylib $DST/
cp /usr/local/opt/fontconfig/lib/libfontconfig.1.dylib $DST/
cp /usr/local/opt/freetype/lib/libfreetype.6.dylib $DST/

